// Unit tests for the fakenet MPC key derivation helpers. Golden vectors were
// generated by running the OLD repo's reference implementation
// (derive-mpc-keys.ts — the same calls the fakenet MPC server makes on its
// root key), so this harness helper is pinned bit-identical to the server.
// The underlying deriveJubjubKeypair golden vectors live in the SDK's own
// schnorr.test.ts.

import { describe, expect, it } from "vitest";

import { deriveMpcKeys, generateMpcRootKey } from "../src/setup/mpc-keys.ts";

// Fixed root key from the golden-vector run (same key as the SDK's
// epsilon-derivation.test.ts MPC_PUBKEY).
const ROOT_KEY = "9e3b2f8d1c4a5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f";
const EXPECTED = {
  jubjubPoint: {
    x: 8023031394973346077785315730014542191880709434026907704830900738402590808213n,
    y: 50101019894250312491238384247378302178175057850557405808701178820769733655529n,
  },
  secp256k1CompressedPubkey: "0x0281e037488c6e708c5a28c8bc2e43b7a704f3a869bd129fb6511bcc58e98db243",
};

describe("deriveMpcKeys", () => {
  interface Case {
    name: string;
    rootKeyHex: string;
  }

  const VALID_FORMS: Case[] = [
    { name: "bare hex root key", rootKeyHex: ROOT_KEY },
    { name: "0x-prefixed root key", rootKeyHex: `0x${ROOT_KEY}` },
    { name: "uppercase hex root key", rootKeyHex: ROOT_KEY.toUpperCase() },
  ];

  it.each(VALID_FORMS)("derives the golden public keys from a $name", ({ rootKeyHex }) => {
    const keys = deriveMpcKeys(rootKeyHex);
    expect(keys.jubjubPoint.x).toBe(EXPECTED.jubjubPoint.x);
    expect(keys.jubjubPoint.y).toBe(EXPECTED.jubjubPoint.y);
    expect(keys.secp256k1CompressedPubkey).toBe(EXPECTED.secp256k1CompressedPubkey);
  });

  const INVALID: Case[] = [
    { name: "too-short key", rootKeyHex: "0xabcd" },
    { name: "too-long key", rootKeyHex: `${ROOT_KEY}00` },
    { name: "non-hex key", rootKeyHex: `zz${ROOT_KEY.slice(2)}` },
    { name: "empty key", rootKeyHex: "" },
  ];

  it.each(INVALID)("rejects a $name", ({ rootKeyHex }) => {
    expect(() => deriveMpcKeys(rootKeyHex)).toThrow(/32 bytes of hex/);
  });
});

describe("generateMpcRootKey", () => {
  it("produces 0x-prefixed 32-byte lowercase hex", () => {
    expect(generateMpcRootKey()).toMatch(/^0x[0-9a-f]{64}$/);
  });

  it("produces a different key on each call", () => {
    expect(generateMpcRootKey()).not.toBe(generateMpcRootKey());
  });
});
