// Unit tests for the fakenet MPC key derivation helpers. The golden vector
// was generated by running the reference implementation (the same call the
// fakenet MPC server makes on its root key), so this harness helper is
// pinned bit-identical to the server. The response-key derivation golden
// vectors live in the SDK's own epsilon-derivation.test.ts.

import { describe, expect, it } from "vitest";

import { deriveMpcKeys, generateMpcRootKey } from "../src/setup/mpc-keys.ts";

// Fixed root key from the golden-vector run (same key as the SDK's
// epsilon-derivation.test.ts MPC_PUBKEY).
const ROOT_KEY = "9e3b2f8d1c4a5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f";
const EXPECTED = {
  secp256k1CompressedPubkey: "0x0281e037488c6e708c5a28c8bc2e43b7a704f3a869bd129fb6511bcc58e98db243",
};

describe("deriveMpcKeys", () => {
  interface Case {
    name: string;
    rootKeyHex: string;
  }

  const VALID_FORMS: Case[] = [
    { name: "bare hex root key", rootKeyHex: ROOT_KEY },
    { name: "0x-prefixed root key", rootKeyHex: `0x${ROOT_KEY}` },
    { name: "uppercase hex root key", rootKeyHex: ROOT_KEY.toUpperCase() },
  ];

  it.each(VALID_FORMS)("derives the golden public key from a $name", ({ rootKeyHex }) => {
    const keys = deriveMpcKeys(rootKeyHex);
    expect(keys.secp256k1CompressedPubkey).toBe(EXPECTED.secp256k1CompressedPubkey);
  });

  const INVALID: Case[] = [
    { name: "too-short key", rootKeyHex: "0xabcd" },
    { name: "too-long key", rootKeyHex: `${ROOT_KEY}00` },
    { name: "non-hex key", rootKeyHex: `zz${ROOT_KEY.slice(2)}` },
    { name: "empty key", rootKeyHex: "" },
  ];

  it.each(INVALID)("rejects a $name", ({ rootKeyHex }) => {
    expect(() => deriveMpcKeys(rootKeyHex)).toThrow(/32 bytes of hex/);
  });
});

describe("generateMpcRootKey", () => {
  it("produces 0x-prefixed 32-byte lowercase hex", () => {
    expect(generateMpcRootKey()).toMatch(/^0x[0-9a-f]{64}$/);
  });

  it("produces a different key on each call", () => {
    expect(generateMpcRootKey()).not.toBe(generateMpcRootKey());
  });
});
