// The single ESLint config for the whole workspace. Every member is linted from
// here: per-package configs would drift, which AGENTS.md bans.
//
// Type-aware rules read the generated src/managed/ types, so `yarn compile`
// must run before `yarn lint`, the same ordering `yarn build` needs.

import js from "@eslint/js";
import vitest from "@vitest/eslint-plugin";
import prettier from "eslint-config-prettier/flat";
import importX from "eslint-plugin-import-x";
import jsdoc from "eslint-plugin-jsdoc";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import { defineConfig, globalIgnores } from "eslint/config";
import tseslint from "typescript-eslint";

/**
 * Package specifiers that reach past a member's curated `src/index.ts` into its
 * generated compiler output. The `./managed/*` subpath export exists only so a
 * runtime can fetch `zkir/`/`keys/` as assets.
 *
 * Only the by-package-name forms are listed. A package reading its own
 * `src/managed/` is legitimate, and a RELATIVE path into another package's
 * output is `import-x/no-relative-packages`' catch.
 */
const MANAGED_DEEP_IMPORTS = [
  "@sig-net/*/managed/**",
  "@sig-net/*/src/managed/**",
  "@midnight-protocol/*/src/managed/**",
];

export default defineConfig([
  // Only generated output that ESLint would otherwise lint. node_modules is
  // ignored by default, and the other gitignored dirs (.yarn, reports, logs,
  // midnight-level-db) hold no JS or TS.
  globalIgnores([
    // compactc output, regenerated by `yarn compile` and gitignored. The glob
    // also covers test-caller-contract's src/managed/SignetSigner symlink,
    // which otherwise walks a file crawler into another package.
    "**/src/managed/**",
    "**/tests/fixtures/managed/**",
    "packages/midnight-serde-conformance/managed/**",
    // Publish-only tsc emit: absent until a published package builds.
    "**/dist/**",
    // hardhat output: absent until `yarn compile:evm` runs.
    "packages/integration-tests/artifacts/**",
    "packages/integration-tests/cache/**",
  ]),

  {
    name: "workspace/typescript",
    files: ["**/*.ts"],
    extends: [
      js.configs.recommended,
      tseslint.configs.strictTypeChecked,
      tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      parserOptions: {
        // The TypeScript project service resolves each file against its own
        // package's nearest tsconfig.json, so a workspace needs no enumerated
        // project list and no tsconfig.eslint.json.
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
    plugins: {
      "import-x": importX,
      "simple-import-sort": simpleImportSort,
    },
    rules: {
      // tsconfig.base.json sets verbatimModuleSyntax, which makes the type-only
      // marker load-bearing rather than cosmetic: an unmarked type import is
      // emitted as a real runtime import.
      "@typescript-eslint/consistent-type-imports": ["error", { fixStyle: "inline-type-imports" }],
      "@typescript-eslint/no-import-type-side-effects": "error",

      // Matches tsc's noUnusedLocals/noUnusedParameters, which already exempt
      // the underscore prefix.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],

      "import-x/no-relative-packages": "error",
      "no-restricted-imports": ["error", { patterns: MANAGED_DEEP_IMPORTS }],

      "simple-import-sort/imports": "error",
      "simple-import-sort/exports": "error",
    },
  },

  {
    name: "workspace/jsdoc",
    files: ["**/src/**/*.ts", "**/deploy.ts"],
    extends: [jsdoc.configs["flat/recommended-typescript-error"]],
    rules: {
      // Every export carries a block. Internal helpers are the author's call.
      "jsdoc/require-jsdoc": [
        "error",
        {
          publicOnly: true,
          require: {
            ArrowFunctionExpression: true,
            ClassDeclaration: true,
            ClassExpression: true,
            FunctionDeclaration: true,
            FunctionExpression: true,
            MethodDefinition: true,
          },
          contexts: [
            "TSEnumDeclaration",
            "TSInterfaceDeclaration",
            "TSTypeAliasDeclaration",
            "TSMethodSignature",
            // Exported consts only. A bare VariableDeclaration selector also
            // matches locals inside function bodies.
            "ExportNamedDeclaration > VariableDeclaration",
          ],
        },
      ],
      "jsdoc/require-throws": "error",
      // The house style separates the description from the first tag with one
      // blank line.
      "jsdoc/tag-lines": ["error", "any", { startLines: 1 }],
    },
  },

  {
    name: "workspace/tests",
    files: ["**/tests/**/*.ts", "**/*.test.ts"],
    extends: [vitest.configs.recommended],
    rules: {
      // An it.only reaching main silently disables the rest of its suite.
      "vitest/no-focused-tests": "error",
      // expectTypeOf is vitest's type-level assertion. Registering it is not a
      // relaxation: the rule's default list simply predates the API.
      "vitest/expect-expect": ["error", { assertFunctionNames: ["expect", "expectTypeOf"] }],
    },
  },

  // This file itself. No disableTypeChecked needed: the type-aware configs are
  // scoped to `files: ["**/*.ts"]`, so they never reach a .js file.
  {
    name: "workspace/config-files",
    files: ["**/*.js", "**/*.mjs"],
    extends: [js.configs.recommended],
  },

  // Last: turns off every rule that would fight Prettier.
  prettier,
]);
