// Unit tests for MPC key derivation. Golden vectors were generated by
// running the OLD repo's reference implementations (derive-mpc-keys.ts +
// signet/schnorr.ts deriveJubjubKeypair — the same calls the MPC server
// makes on its root key), so this port is pinned bit-identical to the server.

import { ecMulGenerator } from "@midnight-ntwrk/compact-runtime";
import { describe, expect, it } from "vitest";

import { deriveJubjubKeypair, deriveMpcKeys, generateMpcRootKey } from "../src/index.ts";

// Fixed root key from the golden-vector run (same key as
// epsilon-derivation.test.ts's MPC_PUBKEY).
const ROOT_KEY = "9e3b2f8d1c4a5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f";
const EXPECTED = {
  jubjubSk: 5081350198549810674173641494209182115841090056686181933241101946253491404819n,
  jubjubPkX: 8023031394973346077785315730014542191880709434026907704830900738402590808213n,
  jubjubPkY: 50101019894250312491238384247378302178175057850557405808701178820769733655529n,
  secp256k1CompressedPubkey: "0x0281e037488c6e708c5a28c8bc2e43b7a704f3a869bd129fb6511bcc58e98db243",
};

describe("deriveMpcKeys", () => {
  interface Case {
    name: string;
    rootKeyHex: string;
  }

  const VALID_FORMS: Case[] = [
    { name: "bare hex root key", rootKeyHex: ROOT_KEY },
    { name: "0x-prefixed root key", rootKeyHex: `0x${ROOT_KEY}` },
    { name: "uppercase hex root key", rootKeyHex: ROOT_KEY.toUpperCase() },
  ];

  it.each(VALID_FORMS)("derives the golden public keys from a $name", ({ rootKeyHex }) => {
    const keys = deriveMpcKeys(rootKeyHex);
    expect(keys.jubjubPkX).toBe(EXPECTED.jubjubPkX);
    expect(keys.jubjubPkY).toBe(EXPECTED.jubjubPkY);
    expect(keys.secp256k1CompressedPubkey).toBe(EXPECTED.secp256k1CompressedPubkey);
  });

  const INVALID: Case[] = [
    { name: "too-short key", rootKeyHex: "0xabcd" },
    { name: "too-long key", rootKeyHex: `${ROOT_KEY}00` },
    { name: "non-hex key", rootKeyHex: `zz${ROOT_KEY.slice(2)}` },
    { name: "empty key", rootKeyHex: "" },
  ];

  it.each(INVALID)("rejects a $name", ({ rootKeyHex }) => {
    expect(() => deriveMpcKeys(rootKeyHex)).toThrow(/32 bytes of hex/);
  });
});

describe("deriveJubjubKeypair", () => {
  it("derives the golden keypair and pk = sk * G", () => {
    const seed = Uint8Array.from(Buffer.from(ROOT_KEY, "hex"));
    const { sk, pk } = deriveJubjubKeypair(seed);
    expect(sk).toBe(EXPECTED.jubjubSk);
    expect(pk.x).toBe(EXPECTED.jubjubPkX);
    expect(pk.y).toBe(EXPECTED.jubjubPkY);
    const recomputed = ecMulGenerator(sk);
    expect(recomputed.x).toBe(pk.x);
    expect(recomputed.y).toBe(pk.y);
  });

  it("is deterministic", () => {
    const seed = Uint8Array.from(Buffer.from(ROOT_KEY, "hex"));
    expect(deriveJubjubKeypair(seed)).toEqual(deriveJubjubKeypair(seed));
  });
});

describe("generateMpcRootKey", () => {
  it("produces 0x-prefixed 32-byte lowercase hex", () => {
    expect(generateMpcRootKey()).toMatch(/^0x[0-9a-f]{64}$/);
  });

  it("produces a different key on each call", () => {
    expect(generateMpcRootKey()).not.toBe(generateMpcRootKey());
  });
});
