// Deploy-tx build test (task.md 2.1 "done when"): runs the Compact
// constructor against the REAL compiled output and wraps the resulting state
// in an unproven deploy transaction. No network, no wallet, no proof server —
// but attaching verifier keys needs `npm run compile:zk` output, so with the
// default --skip-zk output the suite skips (visibly, via the describe title).

import { existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { buildDeployTransaction, makeCompiledContract } from "@midnight-erc20-vault/lib";

import {
  Contract,
  createVaultPrivateState,
  pureCircuits,
  witnesses,
  type VaultPrivateState,
} from "../src/index.ts";

const MANAGED_DIR = fileURLToPath(new URL("../src/managed", import.meta.url));
const HAS_VERIFIER_KEYS = existsSync(join(MANAGED_DIR, "keys"));

// The deployer's identity secret; its commitment is the constructor arg.
const SECRET_KEY = new Uint8Array(32).fill(7);

// Dummy coin public key (32-byte hex) for the constructor context.
const CPK = "0".repeat(64);

describe.skipIf(!HAS_VERIFIER_KEYS)(
  "vault deploy tx (SKIPPED without src/managed/keys — run `npm run compile:zk -w @midnight-erc20-vault/vault-contract`)",
  () => {
    const compiledContract = makeCompiledContract<Contract<VaultPrivateState>, VaultPrivateState>(
      "erc20-vault",
      Contract,
      witnesses,
      MANAGED_DIR,
    );

    it("builds an unproven deploy transaction from the real managed output", async () => {
      const deployTransaction = await buildDeployTransaction(
        compiledContract,
        "undeployed",
        CPK,
        createVaultPrivateState(SECRET_KEY),
        pureCircuits.userCommitment(SECRET_KEY),
      );

      expect(deployTransaction.contractAddress).not.toHaveLength(0);
      expect(deployTransaction.serializedTransaction).toBeInstanceOf(Uint8Array);
      expect(deployTransaction.serializedTransaction.length).toBeGreaterThan(0);
    });

    it("feeds constructorArgs to the Compact constructor (a malformed commitment is rejected)", async () => {
      // The only delta from the passing build above is the 31-byte arg, so the
      // rejection (compact-js wraps the generated Bytes<32> validation error)
      // proves the arg reaches the constructor.
      await expect(
        buildDeployTransaction(
          compiledContract,
          "undeployed",
          CPK,
          createVaultPrivateState(SECRET_KEY),
          new Uint8Array(31), // not Bytes<32> — the generated arg validation must trip
        ),
      ).rejects.toThrow(/Failed to initialize contract/);
    });
  },
);
