// Deploy-tx build test: runs the Compact constructor against the REAL
// compiled output and wraps the resulting state in an unproven deploy
// transaction. No network, no wallet, no proof server — but attaching
// verifier keys needs `yarn compile:zk` output, so with the default
// --skip-zk output the suite skips (visibly, via the describe title).

import { existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { buildDeployTransaction } from "@sig-net/midnight-contract-deploy";
import { secp256k1PublicKeyFromSecretKey } from "@sig-net/midnight";

import { callerCompiledContract, createCallerPrivateState } from "../src/index.ts";

const MANAGED_DIR = fileURLToPath(new URL("../src/managed/signet-caller", import.meta.url));
const HAS_VERIFIER_KEYS = existsSync(join(MANAGED_DIR, "keys"));

// The MPC attestation key the constructor seals.
const MPC_PK = secp256k1PublicKeyFromSecretKey(new Uint8Array(32).fill(0x42));

// Stand-in signet-contract reference sealed as the cross-contract emitter.
const SIGNET_CONTRACT_REF = { bytes: new Uint8Array(32).fill(0x5e) };

// Dummy coin public key (32-byte hex) for the constructor context.
const CPK = "0".repeat(64);

describe.skipIf(!HAS_VERIFIER_KEYS)(
  "caller deploy tx (SKIPPED without src/managed/keys — run `yarn workspace @midnight-protocol/caller-contract compile:zk`)",
  () => {
    it("builds an unproven deploy transaction from the real managed output", async () => {
      const deployTransaction = await buildDeployTransaction(
        callerCompiledContract,
        "undeployed",
        CPK,
        createCallerPrivateState(),
        MPC_PK,
        SIGNET_CONTRACT_REF,
      );

      expect(deployTransaction.contractAddress).not.toHaveLength(0);
      expect(deployTransaction.serializedTransaction).toBeInstanceOf(Uint8Array);
      expect(deployTransaction.serializedTransaction.length).toBeGreaterThan(0);
    });

    it("feeds constructorArgs to the Compact constructor (a malformed signet reference is rejected)", async () => {
      // The only delta from the passing build above is the 31-byte reference,
      // so the rejection (compact-js wraps the generated Bytes<32> validation
      // error) proves the arg reaches the constructor.
      await expect(
        buildDeployTransaction(
          callerCompiledContract,
          "undeployed",
          CPK,
          createCallerPrivateState(),
          MPC_PK,
          { bytes: new Uint8Array(31) }, // not Bytes<32> — the generated arg validation must trip
        ),
      ).rejects.toThrow(/Failed to initialize contract/);
    });
  },
);
